install.packages("vars")
install.packages("shiny")
install.packages("tidyverse")
install.packages("mapproj")
install.packages("maps")
install.packages("devtools")
devtools::install_github("https://github.com/ineswilms/bigtime", ref = "development")
